import { StyleSheet } from "react-native";

const appStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
    padding: 20,
    paddingTop: 80,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#000000",
    marginBottom: 30,
  },
  createAccountButton: {
    backgroundColor: "#00A86B",
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 8,
    marginBottom: 10,
    width: "20%",
    alignItems: "center",
  },
  loginButton: {
    backgroundColor: "#444",
  },
  buttonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
  input: {
    height: 50,
    width: "20%",
    borderColor: "gray",
    borderWidth: 1,
    marginBottom: 15,
    paddingHorizontal: 15,
    borderRadius: 5,
    backgroundColor: "#ffffff",
    textAlign: "left",
  },
  smallText: {
    fontSize: 14,
    color: "#000000",
    fontWeight: "bold",
    marginTop: 20,
    textAlign: "center",
  },
  button: {
    backgroundColor: '#00A86B',
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 8,
    marginBottom: 15,
    marginTop: 10,
    width: "15%",
    alignItems: "center",
  },
  signUpButton: {
    backgroundColor: "#00A86B",
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 8,
    marginTop: 30,
    marginBottom: 15,
    width: "15%",
    alignItems: "center",
  },

  accountButtons: {
    backgroundColor: "#00A86B",
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 8,
    marginTop: 30,
    marginBottom: 15,
    width: "16%",
    alignItems: "center",
  },

  deleteAccountButton: {
    backgroundColor: "#FF0000",
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 8,
    marginTop: 30,
    marginBottom: 15,
    width: "16%",
    alignItems: "center",
  }, 
  secondaryButton: {
    backgroundColor: "#444",
  },
  heading: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 30,
    color: "#333",
    textAlign: "center",
  },
  infoText: {
    fontSize: 18,
    marginBottom: 20,
    color: "#444",
    textAlign: "center",
  },
  bold: {
    fontWeight: "bold",
  },
  // button: {
  //   backgroundColor: "#4A90E2",
  //   padding: 12,
  //   borderRadius: 8,
  //   marginBottom: 15,
  //   alignItems: "center",
  // },
  dangerButton: {
    backgroundColor: "#E94F37",
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    padding: 10,
    marginTop: 10,
    marginBottom: 20,
    borderRadius: 6,
    backgroundColor: "#fff",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.4)",
  },
  modalCard: {
    width: "80%",
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
  },
  modalText: {
    fontSize: 16,
    marginBottom: 20,
    textAlign: "center",
  },
  header: {
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 20,
    textAlign: "center",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 15,
  },
  modalButton: {
    backgroundColor: "#2196F3",
    borderRadius: 5,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  modalButtonText: {
    color: "#fff",
    fontWeight: "bold",
  },
  cancelText: {
    color: "#777",
    marginTop: 10,
    fontSize: 16,
  },
  greyButton: {
    backgroundColor: "#ccc",
  },
  greyButtonText: {
    color: "#333",
    fontSize: 16,
    fontWeight: "600",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  link: {
    color: "#007BFF",
    marginTop: 15,
    textAlign: "center",
    fontWeight: "500",
  },
});

export default appStyles;